--- #-------------------------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
version: "3"

networks:
  connect:
    external:
      name: connect-sandbox
services:
  mongo:
    networks:
      - default
      - connect
    image: "mongo:4.0-xenial"
    ports:
      - "27017:27017"
  api:
    networks:
      - default
      - connect
    build:
      context: api/.
      dockerfile: .devcontainer/Dockerfile
    env_file:
    - docker-compose-vscode.env
    ports:
      - "3001:80"
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock

    command: sleep infinity
  web:
    networks:
      - default
      - connect
    build:
      context: web/.
      dockerfile: .devcontainer/Dockerfile
    env_file:
    - docker-compose-vscode.env
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock

    command: sleep infinity
