apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "az-marketplace-sandbox.fullname" . }}-app
  labels:
    {{- include "az-marketplace-sandbox.labels" . | nindent 4 }}
    {{- include "az-marketplace-sandbox.selectorApp" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "az-marketplace-sandbox.selectorLabels" . | nindent 6 }}
      {{- include "az-marketplace-sandbox.selectorApp" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "az-marketplace-sandbox.selectorLabels" . | nindent 8 }}
        {{- include "az-marketplace-sandbox.selectorApp" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "az-marketplace-sandbox.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: mongoConnectionString
            valueFrom:
              secretKeyRef:
                name: {{ include "az-marketplace-sandbox.fullname" . }}
                key: mongoConnectionString
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
