apiVersion: v1
kind: Service
metadata:
  name: {{ include "az-marketplace-sandbox.fullname" . }}-app
  labels:
    {{- include "az-marketplace-sandbox.labels" . | nindent 4 }}
    {{- include "az-marketplace-sandbox.selectorApp" . | nindent 4 }}
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "az-marketplace-sandbox.selectorLabels" . | nindent 4 }}
    {{- include "az-marketplace-sandbox.selectorApp" . | nindent 4 }}

