{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "az-marketplace-sandbox.serviceAccountName" . }}
  labels:
{{ include "az-marketplace-sandbox.labels" . | nindent 4 }}
{{- end -}}
