name: Deployment [Staging]

on:
  workflow_dispatch:
  release:
    types: [prereleased]

env:
  tag: ${{ github.event.release.tag_name }}
  helmPackageFile: az-marketplace-sandbox-${{ github.event.release.tag_name }}.tgz

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: latamocptechteam/az-marketplace-sandbox
        tags: ${{ github.event.release.tag_name }}
        path: .
        add_git_labels: true
        push: true
    - name: Install Helm Tool
      uses: Azure/setup-helm@v1
      with:
        version: 3.0.0
    - name: Package Project
      run: cd deployment && helm package az-marketplace-sandbox --version ${{ env.tag }} --set image.tag=${{ env.tag }}
    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: deployment/${{ env.helmPackageFile }}
        asset_name: helm-chart.tar
        asset_content_type: application/x-tar
